name: Deploy and Build

on:
    push:
      branches:
          - main

jobs:
    build:
        name: Build Start
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Set up java
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Testing Start
            run: mvn -B test --file pom.xml

          - name: Build
            run: |
                mvn clean
                mvn -B package --file pom.xml

          - name: Upload JAR file
            uses: actions/upload-artifact@v4
            with:
              name: jar-file
              path: target/*.jar

          - name: Build Docker Image
            uses: docker/build-push-action@v3
            with:
              context: .
              file: Dockerfile
              push: false
              tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CICD:$(date +%Y%m%d%H%M%S)
          
          - name: Login to Docker Hub
            uses: docker/login-action@v43
            with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

          - name: Push Docker Image
            uses: docker/build-push-action@v3
            with:
              context: .
              file: Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_HUB_USERNAME }}/CICD:$(date +%Y%m%d%H%M%S)
                
